development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: Aerotage_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: Aerotage_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: Aerotage_production
  pool:     5
  username: postgres
  password: postgres
  template: template0
